//
//  FilmModel.swift
//  CineFileApp
//
//  Created by Ana Luisa Luy on 30/05/25.
//

import Foundation

struct DataModel{
    
    let filmList: [Film] = [
        Film(image:"filme1", title: "Tudo em Todo o Lugar ao Mesmo Tempo", director: "Daniel Kwan, Daniel Scheinert", description: "Uma imigrante chinesa de meia idade se envolve em uma aventura louca, onde só ela pode salvar o mundo explorando outros universos que se conectam com as vidas que ela poderia ter levado.", foto: "filme1capa" ),
        Film(image:"filme2", title: "Cisne Negro", director: "Darren Aronofsky", description: "Uma esforçada bailarina luta para manter sua sanidade após obter o papel principal no Lago dos Cisnes de Tchaikovsky.", foto: "filme2capa"),
        Film(image:"filme3", title: "Barbie a princesa e a plebeia", director: "William Lau", description: "Uma plebeia, moradora de um vilarejo, é muito parecida com a princesa do reino. Os destinos das duas se cruzam quando a princesa é sequestrada, e a moça humilde usa sua incrível semelhança com ela para tentar salvar das mãos do vilão.", foto: "filme3capa"),
        Film(image:"filme4", title: "Show de Truman ", director: "Peter Weir", description: "Truman Burbank é um pacato vendedor de seguros que leva uma vida simples com sua esposa Meryl Burbank. Porém, algumas coisas ao seu redor fazem com que ele passe a estranhar sua cidade, seus supostos amigos e até sua mulher. Após conhecer a misteriosa Lauren, ele fica intrigado e acaba descobrindo que toda sua vida foi monitorada por câmeras e transmitida em rede nacional.", foto: "filme4capa"),
        Film(image:"filme5", title: "Spirit: O Corcel Indomável", director: "Kelly Asbury, Lorna Cook", description: "Animação sobre a amizade entre um menino indígena e um cavalo indomável apaixonado por uma égua. Ambientada no Velho Oeste americano, mostra o impacto do processo civilizatório na vida dos três e também na amizade que construíram.", foto: "filme5capa"),
        Film(image:"filme6", title: "Labirinto do Fauno", director: "Guillermo del Toro", description: "Em 1944, na Espanha, a jovem Ofélia e sua mãe doente chegam ao posto do novo marido de sua mãe, um sádico oficial do exército que está tentando reprimir uma guerrilheira. Enquanto explorava um labirinto antigo, Ofélia encontra o Pan fauno, que diz que a menina é uma lendária princesa perdida e que ela precisa completar três tarefas perigosas a fim de se tornar imortal.", foto: "filme6capa"),
        Film(image:"filme7", title: "O Predestinado", director: "Michael Spierig, Peter Spierig", description: "Um agente precisa viajar no tempo para impedir a ação de um criminoso responsável por um ataque que mata milhares de pessoas.", foto: "filme7capa"),
        Film(image:"filme8", title: "Gigantes de aço", director: "Shawn Levy", description: "Em um futuro próximo, as máquinas substituem os homens no ringue. As lutas de boxe acontecem entre robôs de alta tecnologia. Charlie, um ex-lutador frustrado, decide se juntar ao filho para construir um competidor imbatível.", foto: "filme8capa"),
        Film(image:"filme9", title: "A vastidão da noite", director: "Andrew Patterson", description: "Duas crianças procuram a fonte de uma misteriosa frequência que surgiu em sua cidade.", foto: "filme9capa"),
        Film(image:"filme10", title: "Parasita", director: "Bong Joon-ho", description: "Toda a família de Ki-taek está desempregada, vivendo em um porão sujo e apertado. Por obra do acaso, ele começa a dar aulas de inglês para uma garota de família rica. Fascinados com a vida luxuosa destas pessoas, pai, mãe e filhos bolam um plano para se infiltrar também na abastada família, um a um. No entanto, os segredos e mentiras necessários à ascensão social cobram o seu preço.", foto: "filme10capa"),
        Film(image:"filme11", title: "Passivonas", director: "Emma Seligman", description: "Duas alunas não populares do último ano do ensino médio criam um clube da luta para tentar impressionar e conquistar líderes de torcida.", foto: "filme11capa"),
        Film(image:"filme12", title: "Turma da mônica: uma aventura no tempo", director: "Mauricio de Sousa", description: "Franjinha está construindo uma máquina do tempo e precisa reunir moléculas dos quatro elementos: ar, água, fogo e terra. Mônica joga Sansão e, sem querer, acerta o aparelho, espalhando os elementos. Agora a turma precisa consertá-la.", foto: "filme12capa"),
        Film(image:"filme13", title: "Amnésia (Memento)", director: "Christopher Nolan", description: "Leonard está caçando o homem que estuprou e matou sua esposa. Ele tem dificuldades em encontrar o assassino pois sofre de uma forma intratável de perda de memória. Mesmo que ele possa lembrar detalhes da vida antes do acidente, Leonard não consegue lembrar o que aconteceu quinze minutos atrás, onde está indo ou a razão.", foto: "filme13capa"),
        Film(image:"filme14", title: "Os Excêntricos Tenenbaums", director: "Wes Anderson", description: "Royal e sua esposa Etheline tiveram três filhos muito diferentes entre si, mas igualmente bem-sucedidos. Quando Etheline resolve se casar com outro, o irresponsável e excêntrico Royal resolve lutar por seu amor reunindo toda a família.", foto: "filme14capa"),
        Film(image:"filme15", title: "La la Land", director: " Damien Chazelle", description: "O pianista Sebastian conhece a atriz Mia, e os dois se apaixonam perdidamente. Em busca de oportunidades para suas carreiras na competitiva Los Angeles, os jovens tentam fazer o relacionamento amoroso dar certo, enquanto perseguem fama e sucesso.", foto: "filme15capa"),
        Film(image:"filme16", title: "Os Serviços de Entrega da Kiki", director: "Hayao Miyazaki", description: "Por ordem de sua mãe, Kiki parte para um aprendizado de um ano, acompanhada por seu gato preto. A um comando de sua vassoura mágica, ela vai parar na charmosa cidadezinha de Moreoastal. Infelizmente, os hotéis locais não aceitam bruxas e a polícia a flagra fazendo algumas travessuras.", foto: "filme16capa"),
        Film(image:"filme17", title: "O Feitiço de Áquila", director: "Richard Donner", description: " O ladrão Gaston escapa da masmorra medieval de Aquila através da latrina. Os soldados estão prestes a matá-lo quando Navarra o salva. Navarra, viajando com seu falcão animado, planeja matar o bispo de Áquila com a ajuda de Gaston.", foto: "filme17capa"),
        Film(image:"filme18", title: "Os incríveis", director: "Brad Bird", description: " Depois do governo banir o uso de superpoderes, o maior herói do planeta, o Sr. Incrível, vive de forma pacata com sua família. Apesar de estar feliz com a vida doméstica, o Sr. Incrível ainda sente falta dos tempos em que viveu como super-herói, e sua grande chance de entrar em ação novamente surge quando um velho inimigo volta a atacar. Só que agora ele precisa contar com a ajuda de toda a família para vencer o vilão.", foto: "filme18capa"),
        
        
            ]
        }
